### ISSUE TITLE
not compatible with Laravel 6

### ISSUE THREAD

**Issue by vesper8** [mtolhuys/laravel-database-synchronizer#29]
As a result of the hard dependencies in your composer.json, this cannot currently be installed on Laravel 6

Perhaps remove some of the dependencies that are already part of the Laravel dependencies.. and for the others.. could you also make it available for v6 please?

Thank you!

**Comment by mtolhuys** [comment]
Hi @vesper8, 

Thanks for mentioning! Development has been pretty quiet on this one for a while. Will pick it up asap.

**Comment by vesper8** [comment]
@mtolhuys it's probably just a matter of updating the composer.json to allow for the latest dependencies.. unlikely that any work beyond that is required though I can't be sure.. any chance you could commit this change soon? I would like to use this in my Laravel 6 app

also, since Laravel 7 is now just around the corner, you could pre-emptively also allow for those versions ahead of time

for example:
```
"illuminate/support": "~5|~6|~7",
"phpunit/phpunit": "~7.0|~8.0|~9.0",
```
thank you

**Comment by mtolhuys** [comment]
Hi @vesper8, thanks for the reminder, I'll update it today.

**Comment by vesper8** [comment]
sweet!

I did just fork your package and this allowed me to install on Laravel 6. I didn't run any tests yet however https://github.com/vesper8/laravel-database-synchronizer/blob/master/composer.json

**Comment by mtolhuys** [comment]
@vesper8 I think you can update / (re)install the package in your projects now! I've also added a little confirmation dialog before the process starts for safety.

**Comment by vesper8** [comment]
@mtolhuys Hey hey! It's been a while but I'm still using this package and tonight I'm upgrading my project to Laravel 8 and this one's causing problems again. This time it looks like just adding 

```
    "require": {
        "illuminate/support": "~5|~6|~7|~8",
        "doctrine/dbal":"~2.3",
        "ext-pdo": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "~7.0|~8.0|~9.0|~10.0",
        "mockery/mockery": "^1.1",
        "orchestra/testbench": "~3.0|~4.0|~5.0|~6.0",
        "sempro/phpunit-pretty-print": "^1.0"
    },
```

Isn't enough.. that must be because one of the dependencies themselves also needs to be upgraded but I'm not sure.. I just know I can't install it on Laravel 8 easily

Since you're much more familiar with this project.. would be great if you had a bit of spare time to look at it and see if you can get it compatible with Laravel 7 and 8 (mostly 8)

Many thanks!

**Comment by mtolhuys** [comment]
Hi @vesper8 ! hahah long time no see. Nice to hear you're still using it. :) 

I've bumped the composer.json, should be good to go!

**Comment by vesper8** [comment]
@mtolhuys thank you : )

However there seems to be a problem with the tag as the new `0.3.6` is not available on https://packagist.org/packages/mtolhuijs/laravel-database-synchronizer and is also not available to be installed via composer. The latest remains `0.3.4`

Would appreciate it if you could look into what went wrong there. Many thanks!
