### ISSUE TITLE
not synchronizing deleted and updated records

### ISSUE THREAD

**Issue by nirajank** [mtolhuys/laravel-database-synchronizer#30]
Hello sir, it is not working and synchronizing for deleted and updated records

**Comment by mtolhuys** [comment]
Hi @nirajank, 

Correct, on default it will only add new rows or update ones found by the query column from production to your staging database. 

You could, however, make a copy of the state of your production database by using the --truncate option which will do a `migrate:refresh` on your staging database. This would then also synchronize the deleted records. 

Hope that helps!
